### PR TITLE
script .js import corrections

### PR DESCRIPTION
**Pull request by Xt-Man**

### CODE REVIEW

**Comment by Limraj** [comment]
@Xt-Man What happened here?

**Comment by Xt-Man** [comment]
Sorry @Limraj , I pushed by mistake

**Comment by Limraj** [comment]
@Xt-Man Everything's all right. If you want to improve these imports, then create an issue for it and propose a fix.

**Comment by Xt-Man** [comment]
@Limraj Ok, I got it.

**Pull request closed without merging**
