### PR TITLE
Initial support for TANGO Controls protocol

### PR DESCRIPTION
**Pull request by kinsamanka**
Issue #2135

### CODE REVIEW

**Comment by kinsamanka** [comment]
I've re-based the PR instead of creating a new one. I hope this is OK.

**Comment by Limraj** [comment]
@kinsamanka I transferred these changes, with some small corrections, could you please review this code, in the docker the tag with these changes is pr-2141.

https://github.com/SCADA-LTS/Scada-LTS/pull/2141 

Best wishes.

**Comment by kinsamanka** [comment]
Thanks, I will look into the changes.

I am also planning to add the code for the new UI, would it be better to file a new PR for that?

**Comment by Limraj** [comment]
@kinsamanka It would be good to create an issue for Tango and the new ui, but for now I would suggest not to implement, wait until version 2.7.1 is released. New issue, you can connect to the issue: https://github.com/SCADA-LTS/Scada-LTS/issues/2143 . Perhaps you would like to help us in testing version 2.7.1?

**Comment by kinsamanka** [comment]
Yes, no rush on my part. I still need to understand the codebase. :smiley:

**Pull request closed without merging**
