### PR TITLE
Chart visible fixed

### PR DESCRIPTION
**Pull request by Xt-Man**
When stop live chart, the function switchChartMode sets display "none" to imageChartDiv, but the function getImageChart doesn´t set display 'table-cell' again

### CODE REVIEW

**Comment by Limraj** [comment]
Hi @Xt-Man,
First, we create an issue with the problem (with scenario), next branch with number and title issue, then a fix and a pull request. :)

**Comment by Limraj** [comment]
https://github.com/SCADA-LTS/Scada-LTS/issues/2452

**Comment by Limraj** [comment]
created an Issue: https://github.com/SCADA-LTS/Scada-LTS/issues/2452
When I tried to reproduce the problem, I found another bug that had the same cause, starting live, stopping and starting caused the live chart to stop refreshing.

pullrequest: https://github.com/SCADA-LTS/Scada-LTS/pull/2453

**Comment by Limraj** [comment]
@Xt-Man Could you do a code review and test it? https://github.com/SCADA-LTS/Scada-LTS/pull/2453 test scenario: https://github.com/SCADA-LTS/Scada-LTS/issues/2452

**Comment by Xt-Man** [comment]
Hi @Limraj , i reviewed  and tested it. Seems ok to me.
But i found another, the "Get Chart" shows an alert "Error marshalling int: Format error converting 419.77778. See the logs for more details." if you set your browser do 90% zoom, or the same message with a different number if your zoom in 110%.
Should i create a new issue?

**Comment by Limraj** [comment]
<s>
1. Did you get this error when following the steps from the scenario in the issue? If not, write step by step how to recreate it. Paste the stacktrace from the log. 
2. Please send me your configuration. Import/Export -> Export Project -> zip file.

First we need to determine what is causing the error. 
Once we gather information about it, then you will be able to create an issue.
</s>

edit:
So you resized in your browser and that led to this error? Then create an issue for it, add a scenario.

**Pull request closed without merging**
