### PR TITLE
#2135 Support for TANGO Controls protocol - java 11 in build.xml; sup…

### PR DESCRIPTION
**Pull request by Limraj**
…port Tango

### CODE REVIEW

**Comment by kinsamanka** [comment]
These additional libs are needed:
```
jacorb-3.9.jar
jacorb-omgapi-3.9.jar
jacorb-services-3.9.jar
jboss-rmi-api_1.0_spec-1.0.6.Final.jar
jeromq-0.5.1.jar
TangORB-9.6.8.jar
```

This one is not used:
```
glassfish-corba-omgapi-3.2.0-b005.jar
```

**Comment by Limraj** [comment]
@kinsamanka The problem occurs in runtime? Are you using the simulator Tango? 
Could you please send me the logs from tomcat for to the following address: kamil.jarmusik@softq.pl?

Best wishes.

**Comment by kinsamanka** [comment]
Those libs are runtime requirements.

These are the relevant log entries:
```
ts-scada_lts   | INFO  2022-03-23T12:34:57,315 (com.serotonin.mango.rt.RuntimeManager.initializeDataSource:382) - Data source 'openplc' initialized 
ts-scada_lts   | java.lang.ClassNotFoundException: fr.esrf.TangoApi.factory.DefaultTangoFactoryImpl
ts-scada_lts   |        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1407)
ts-scada_lts   |        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1215)
ts-scada_lts   |        at java.base/java.lang.Class.forName0(Native Method)
ts-scada_lts   |        at java.base/java.lang.Class.forName(Unknown Source)
ts-scada_lts   |        at fr.esrf.Tango.factory.TangoFactory.getObject(TangoFactory.java:116)
ts-scada_lts   |        at fr.esrf.Tango.factory.TangoFactory.initTangoFactory(TangoFactory.java:154)
ts-scada_lts   |        at fr.esrf.Tango.factory.TangoFactory.<init>(TangoFactory.java:72)
ts-scada_lts   |        at fr.esrf.Tango.factory.TangoFactory.<clinit>(TangoFactory.java:66)
ts-scada_lts   |        at fr.esrf.TangoApi.Connection.<init>(Connection.java:197)
ts-scada_lts   |        at fr.esrf.TangoApi.DeviceProxy.<init>(DeviceProxy.java:143)
ts-scada_lts   |        at com.serotonin.mango.rt.dataSource.tango.TangoDataSourceRT.initialize(TangoDataSourceRT.java:55)
ts-scada_lts   |        at com.serotonin.mango.rt.RuntimeManager.initializeDataSource(RuntimeManager.java:369)
ts-scada_lts   |        at com.serotonin.mango.rt.RuntimeManager.initialize(RuntimeManager.java:177)
ts-scada_lts   |        at com.serotonin.mango.MangoContextListener.runtimeManagerInitialize(MangoContextListener.java:513)
ts-scada_lts   |        at com.serotonin.mango.MangoContextListener.contextInitialized(MangoContextListener.java:135)
ts-scada_lts   |        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4768)
ts-scada_lts   |        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5230)
ts-scada_lts   |        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
ts-scada_lts   |        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:726)
ts-scada_lts   |        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:698)
ts-scada_lts   |        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:696)
ts-scada_lts   |        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1024)
ts-scada_lts   |        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1911)
ts-scada_lts   |        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
ts-scada_lts   |        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
ts-scada_lts   |        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
ts-scada_lts   |        at java.base/java.util.concurrent.AbstractExecutorService.submit(Unknown Source)
ts-scada_lts   |        at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:825)
ts-scada_lts   |        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:475)
ts-scada_lts   |        at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1618)
ts-scada_lts   |        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:319)
ts-scada_lts   |        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
ts-scada_lts   |        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
ts-scada_lts   |        at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
ts-scada_lts   |        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:946)
ts-scada_lts   |        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:835)
ts-scada_lts   |        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
ts-scada_lts   |        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396)
ts-scada_lts   |        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386)
ts-scada_lts   |        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
ts-scada_lts   |        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
ts-scada_lts   |        at java.base/java.util.concurrent.AbstractExecutorService.submit(Unknown Source)
ts-scada_lts   |        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)
ts-scada_lts   |        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:263)
ts-scada_lts   |        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
ts-scada_lts   |        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:432)
ts-scada_lts   |        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
ts-scada_lts   |        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:927)
ts-scada_lts   |        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
ts-scada_lts   |        at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
ts-scada_lts   |        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
ts-scada_lts   |        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
ts-scada_lts   |        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
ts-scada_lts   |        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
ts-scada_lts   |        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
ts-scada_lts   |        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:476)
ts-scada_lts   | ERROR 2022-03-23T12:34:57,321 (com.serotonin.mango.rt.dataSource.tango.TangoDataSourceRT.initialize:60) - Failed to connect to device: tango://ts-databaseds:10000/sys/tg_test/1 
ts-scada_lts   | INFO  2022-03-23T12:34:57,332 (com.serotonin.mango.rt.RuntimeManager.initializeDataSource:382) - Data source 'tango' initialized 
ts-scada_lts   | INFO  2022-03-23T12:34:57,356 (com.serotonin.mango.MangoContextListener.contextInitialized:156) - Scada-LTS context started 
ts-scada_lts   | INFO  2022-03-23T12:34:57,362 (com.serotonin.mango.MangoContextListener.contextInitialized:159) - Cache point hierarchy initialized 
```

**Comment by Limraj** [comment]
I uploaded these libraries. How do you configure the test environment for Tango?

**Comment by Limraj** [comment]
We can still try with the jar from here: https://gitlab.com/tango-controls/JTango/-/releases

It looks like e.g. JTango-9.6.8-openjdk_11 is a jar containing all the necessary dependencies. What do you think?

**Comment by kinsamanka** [comment]
This is working now. Thanks.

I've used `docker-compose` to set these up but it is still WIP. I'll share it once it is OK.

`JTango-9.6.8-openjdk_11` uses a newer version of the Quartz library which is not compatible with the existing one.

**Comment by Limraj** [comment]
Okay. That set of libraries we implemented don't conflict with ours? How do you check it?

But I would also like to test it and wonder how to configure the Tango environment. I found a few places with libraries that facilitate simulating the Tango server, but maybe you already have a ready-made solution?

**Comment by kinsamanka** [comment]
Those set of libraries are the minimum required to run this [sample code](https://www.esrf.fr/computing/cs/tango/tango_doc/kernel_doc/tango_java_api/help/EventWithCallbacks.html). (I have to figure this out by hand because using `JTango-9.6.8-openjdk_11` would not allow Scada-LTS to start)

There's already an existing [tango test server](https://gitlab.com/tango-controls/TangoTest) but it needs a working Tango stack.

There is this one too: https://tango-controls.readthedocs.io/en/latest/tutorials-and-howtos/how-tos/how-to-use-tango-servers-without-db.html but I haven't tried it yet.

The quickest way to setup Tango is to use [TangoBox](https://tango-controls.readthedocs.io/en/latest/installation/vm/tangobox.html). 

I have a ready-made solution but it is still very rough; I'm still in the process of figuring things out.

Is there an existing unit test for a datasource that I can look into? Java is not really my go-to language :wink:

**Comment by Limraj** [comment]
@kinsamanka Thanks.
As for the test scenarios, I meant tests from the user's perspective. 
We create unit tests for complex logic. 
We try to make unit tests not timed so that they produce the same result every time, I think it might be difficult to achieve with multi-threaded tests.

Best wishes.

**Comment by kinsamanka** [comment]
This is my setup for testing:

https://github.com/kinsamanka/tango_scada-lts

and the sample config:

```json
{
   "dataSources":[
      {
         "xid":"DS_483334",
         "type":"TANGO",
         "alarmLevels":{
            "POINT_READ_EXCEPTION_EVENT":"URGENT",
            "POINT_WRITE_EXCEPTION_EVENT":"URGENT",
            "DATA_SOURCE_EXCEPTION":"URGENT"
         },
         "deviceID":"sys\/tg_test\/1",
         "enabled":true,
         "hostName":"databaseds",
         "name":"tango",
         "port":10000
      }
   ],
   "dataPoints":[
      {
         "xid":"DP_907797",
         "loggingType":"ON_CHANGE",
         "intervalLoggingPeriodType":"MINUTES",
         "intervalLoggingType":"INSTANT",
         "purgeType":"YEARS",
         "pointLocator":{
            "dataType":"NUMERIC",
            "attribute":"double_scalar",
            "settable":true
         },
         "eventDetectors":[
         ],
         "engineeringUnits":"",
         "chartColour":null,
         "chartRenderer":null,
         "dataSourceXid":"DS_483334",
         "defaultCacheSize":1,
         "description":null,
         "deviceName":"tango",
         "discardExtremeValues":false,
         "discardHighLimit":1.7976931348623157E308,
         "discardLowLimit":-1.7976931348623157E308,
         "enabled":true,
         "eventTextRenderer":{
            "type":"EVENT_NONE"
         },
         "intervalLoggingPeriod":15,
         "name":"double_scalar",
         "purgePeriod":1,
         "textRenderer":{
            "type":"PLAIN",
            "suffix":""
         },
         "tolerance":0.0
      }
   ]
}
```

**Comment by Limraj** [comment]
Hello @kinsamanka,
we want to add this to version 2.7.2, so I swapped out these changes:
https://github.com/SCADA-LTS/Scada-LTS/pull/2230

Best wishes.

**Pull request closed without merging**
