### PR TITLE
Major Upgrade on Nodejs version

### PR DESCRIPTION
**Pull request by RenatoExpert**
**This patch is underdevelopment, not ready to be merged!**

# Major upgrade on Nodejs version
## Goals
- [x] Make vue project from scadalts-ui directory to work using last version of node and npm
- [x] Make automatic compilation with docker and docker compose
- [x] Resolve minor issues from its migration

## What I am doing
### Vue project
In order to make `npm install` to work without error, I had to remove `sinon` and upgrade `cypress` and `@vue/cli-plugin-e2e-cypress`.
I will try to give sinon back, adapt everything to the new dependencies and fix all warnings before finish this pull request.
That was just to save time going first at main goal, and then resolving minor issues from it.
### Gradle
I removed every npm command from gradle, to be more specific: from `scadalts-ui/build.gradle`.
Docker seems to be more efficient at this point, but I need to experiment a bit more at this topic, and also I am open to give it back to gradle if this is better at end.
### Dockerfile
I got all npm build process into the same Dockerfile
### Compose
I made compose to use local built docker image, instead of downloading from internet

## Console Demonstration
### Compile
```
[renato@zosoarch Scada-LTS]$ docker compose up -d 
[+] Running 1/1
 ! scadalts Warning                                                                                                                                                                                                                      2.8s 
[+] Building 413.5s (29/29) FINISHED                                                                                                                                                                                           docker:default
 => [scadalts internal] load .dockerignore                                                                                                                                                                                               0.2s
 => => transferring context: 2B                                                                                                                                                                                                          0.0s
 => [scadalts internal] load build definition from Dockerfile                                                                                                                                                                            0.3s
 => => transferring dockerfile: 1.30kB                                                                                                                                                                                                   0.0s
 => [scadalts internal] load metadata for docker.io/library/node:21.4                                                                                                                                                                    3.9s
 => [scadalts internal] load metadata for docker.io/library/gradle:7.3                                                                                                                                                                   0.0s
 => [scadalts internal] load metadata for docker.io/library/tomcat:9.0.53                                                                                                                                                                0.0s
 => [scadalts scadalts-ui 1/5] FROM docker.io/library/node:21.4@sha256:814a6dc5bfd4ecc5ef24652f6b4f2790e9f3552b52ee38a7b51fc4d4c0d6d7fd                                                                                                131.5s
 => => resolve docker.io/library/node:21.4@sha256:814a6dc5bfd4ecc5ef24652f6b4f2790e9f3552b52ee38a7b51fc4d4c0d6d7fd                                                                                                                       3.2s
 => => sha256:5aeb975d4a5c53f930d848c6d40af3b11232bf7679acae74201c40d5136dc97c 7.53kB / 7.53kB                                                                                                                                           0.0s
 => => sha256:814a6dc5bfd4ecc5ef24652f6b4f2790e9f3552b52ee38a7b51fc4d4c0d6d7fd 1.21kB / 1.21kB                                                                                                                                           0.0s
 => => sha256:fdee4f1d341a7ffeb2b9f770293a9a216c7a72c962edbe08dffa493c27265a59 2.00kB / 2.00kB                                                                                                                                           0.0s
 => => sha256:bc0734b949dcdcabe5bfdf0c8b9f44491e0fce04cb10c9c6e76282b9f6abdf01 49.56MB / 49.56MB                                                                                                                                        26.4s
 => => sha256:917ee5330e73737d6095a802333d311648959399ff2c067150890162e720f863 64.13MB / 64.13MB                                                                                                                                        55.5s
 => => sha256:b5de22c0f5cd2ea2bb6c0524478db95bff5a294c99419ccd4a9d3ccc9873bad9 24.05MB / 24.05MB                                                                                                                                        27.2s
 => => sha256:b43bd898d5fbe0e1606380820047fd1e8b421722c9e69ac12757474305bd6702 211.10MB / 211.10MB                                                                                                                                     104.3s
 => => extracting sha256:bc0734b949dcdcabe5bfdf0c8b9f44491e0fce04cb10c9c6e76282b9f6abdf01                                                                                                                                                2.7s
 => => sha256:9b5852c9e7e7085c3f6de31e692245df85fa0ad9291c75b6d7ff176dfd7e7b79 3.37kB / 3.37kB                                                                                                                                          27.7s
 => => sha256:1e930799abcd18132ad0f78465a5f82b21d5523b665286c5c2ffb50b2259304f 49.13MB / 49.13MB                                                                                                                                        71.5s
 => => extracting sha256:b5de22c0f5cd2ea2bb6c0524478db95bff5a294c99419ccd4a9d3ccc9873bad9                                                                                                                                                1.4s
 => => extracting sha256:917ee5330e73737d6095a802333d311648959399ff2c067150890162e720f863                                                                                                                                                3.6s
 => => sha256:6a42039d44843b69013d5d9774e730d4cd57d85d86e73886683cdb3ae654cb4a 2.23MB / 2.23MB                                                                                                                                          58.6s
 => => sha256:bbc28c108ee5c9f694018e70972e087b7d1bfd875aba8a37a695ed79326c1b50 451B / 451B                                                                                                                                              60.0s
 => => extracting sha256:b43bd898d5fbe0e1606380820047fd1e8b421722c9e69ac12757474305bd6702                                                                                                                                               10.3s
 => => extracting sha256:9b5852c9e7e7085c3f6de31e692245df85fa0ad9291c75b6d7ff176dfd7e7b79                                                                                                                                                0.0s
 => => extracting sha256:1e930799abcd18132ad0f78465a5f82b21d5523b665286c5c2ffb50b2259304f                                                                                                                                                3.4s
 => => extracting sha256:6a42039d44843b69013d5d9774e730d4cd57d85d86e73886683cdb3ae654cb4a                                                                                                                                                0.3s
 => => extracting sha256:bbc28c108ee5c9f694018e70972e087b7d1bfd875aba8a37a695ed79326c1b50                                                                                                                                                0.0s
 => [scadalts internal] load build context                                                                                                                                                                                              15.8s
 => => transferring context: 859.56MB                                                                                                                                                                                                   13.0s
 => [scadalts war-compiler 1/5] FROM docker.io/library/gradle:7.3                                                                                                                                                                        3.4s
 => [scadalts scadalts-tomcat  1/11] FROM docker.io/library/tomcat:9.0.53                                                                                                                                                                3.6s
 => [scadalts war-compiler 2/5] WORKDIR /home/gradle                                                                                                                                                                                     0.8s
 => [scadalts scadalts-tomcat  2/11] WORKDIR /usr/local/tomcat/                                                                                                                                                                          0.7s
 => [scadalts war-compiler 3/5] COPY . .                                                                                                                                                                                                20.5s
 => [scadalts scadalts-tomcat  3/11] COPY WebContent/WEB-INF/lib/mysql-connector-java-5.1.49.jar ./lib/mysql-connector-java-5.1.49.jar                                                                                                  20.6s
 => [scadalts scadalts-tomcat  4/11] COPY tomcat/lib/activation.jar ./lib/activation.jar                                                                                                                                                 0.5s
 => [scadalts scadalts-tomcat  5/11] COPY tomcat/lib/jaxb-api-2.4.0-b180830.0359.jar ./lib/jaxb-api-2.4.0-b180830.0359.jar                                                                                                               2.1s
 => [scadalts scadalts-tomcat  6/11] COPY tomcat/lib/jaxb-core-3.0.2.jar ./lib/jaxb-core-3.0.2.jar                                                                                                                                       0.5s
 => [scadalts scadalts-tomcat  7/11] COPY tomcat/lib/jaxb-runtime-2.4.0-b180830.0438.jar ./lib/jaxb-runtime-2.4.0-b180830.0438.jar                                                                                                       0.4s
 => [scadalts scadalts-ui 2/5] WORKDIR /src                                                                                                                                                                                              0.1s
 => [scadalts scadalts-ui 3/5] COPY ./scadalts-ui .                                                                                                                                                                                     15.8s
 => [scadalts scadalts-ui 4/5] RUN npm install                                                                                                                                                                                          44.6s
 => [scadalts scadalts-ui 5/5] RUN npm run build                                                                                                                                                                                        85.9s 
 => [scadalts war-compiler 4/5] COPY --from=scadalts-ui /src/* ./scadalts-ui/                                                                                                                                                            8.0s 
 => [scadalts war-compiler 5/5] RUN gradle war                                                                                                                                                                                          69.3s 
 => [scadalts war-file 1/2] COPY --from=war-compiler /home/gradle/build/libs/Scada-LTS.war/ Scada-LTS.war                                                                                                                                0.7s 
 => [scadalts scadalts-tomcat  8/11] COPY --from=war-file /Scada-LTS.war ./webapps                                                                                                                                                       0.4s 
 => [scadalts scadalts-tomcat  9/11] RUN cd ./webapps/ && mkdir Scada-LTS && unzip Scada-LTS.war -d Scada-LTS                                                                                                                            5.5s 
 => [scadalts scadalts-tomcat 10/11] COPY docker/config/context.xml ./webapps/Scada-LTS/META-INF/context.xml                                                                                                                             0.2s 
 => [scadalts scadalts-tomcat 11/11] RUN apt update && apt install -y wait-for-it && apt clean && rm -rf /var/lib/apt/lists/*                                                                                                            8.1s 
 => [scadalts] exporting to image                                                                                                                                                                                                        3.7s 
 => => exporting layers                                                                                                                                                                                                                  3.7s 
 => => writing image sha256:d241a996b99ddd2d40837227933069c912bcc975418b78aaef4784910e06a60a                                                                                                                                             0.0s 
 => => naming to docker.io/library/scadalts:latest                                                                                                                                                                                       0.0s 
[+] Running 3/3                                                                                                                                                                                                                               
 ✔ Network scada-lts_default       Created                                                                                                                                                                                               0.3s 
 ✔ Container mysql                 Started                                                                                                                                                                                               0.5s 
 ✔ Container scada-lts-scadalts-1  Started                                                                                                                                                                                               0.2s 
```

### Docker processes/containers
```
[renato@zosoarch Scada-LTS]$ docker ps
CONTAINER ID   IMAGE                       COMMAND                  CREATED          STATUS                             PORTS                                                        NAMES
0f00b6ae7c5e   scadalts:latest             "/usr/bin/wait-for-i…"   46 seconds ago   Up 6 seconds                       8000/tcp, 0.0.0.0:8080->8080/tcp, :::8080->8080/tcp          scada-lts-scadalts-1
7105cbb068c1   mysql/mysql-server:8.0.32   "/entrypoint.sh --lo…"   46 seconds ago   Up 44 seconds (health: starting)   0.0.0.0:3306->3306/tcp, :::3306->3306/tcp, 33060-33061/tcp   mysql
```

### Testing connectivity from Tomcat
```
[renato@zosoarch Scada-LTS]$ curl 192.168.1.101:8080
<!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class="line" /><h3>Apache Tomcat/9.0.53</h3></body></html>
```

## Screenshots
To ensure everything got OK at compilation, specially on frontend(/scadalts-ui), which is the most affected component
![Screen Shot 2023-12-24 at 21 10 22](https://github.com/SCADA-LTS/Scada-LTS/assets/20760510/584a8333-6586-4dde-9381-a33bab917b89)
![Screen Shot 2023-12-24 at 21 10 31](https://github.com/SCADA-LTS/Scada-LTS/assets/20760510/6e45e79d-852e-4745-92df-c5238c448bd2)
![Screen Shot 2023-12-24 at 21 10 48](https://github.com/SCADA-LTS/Scada-LTS/assets/20760510/0b179bff-ed2d-4101-b76f-7128f5edbf1c)

### CODE REVIEW

**Comment by Limraj** [comment]
Hi @RenatoExpert,
I meant only node upgrade, with minimal, necessary changes, i.e. expected changes:
- upgrade node version lts (min 20, nice 22, best 24);
- upgrade versions for other js library (to the minimum version on which the build works);
- updating supported node versions in the wiki: (if you have the permission)
https://github.com/SCADA-LTS/Scada-LTS/wiki/Getting-started-Development-%E2%80%90-Linux
https://github.com/SCADA-LTS/Scada-LTS/wiki/Getting-started-Development-%E2%80%90-Windows

Unexpected changes include:
- anything from "java"; (the backend has nothing to do with the frontend created using vue for which we need node)
- anything from Dockerfile (at the stage of creating the Docker image we already have a war file, so this is already the project building/compilation stage, all npm calls should be made before the war file is created, check what tasks gradle is doing with the word 'build');
- changes gradle files; (if not necessary)
- remove the library;
- changes to the source code;  (if not necessary)

I guess it's worth starting over. 
Advice:
1. Create issue with upgrade node;
2. First of all, we try to build an application using Node 20, if we are successful, we move on to version: 22 and finally 24, if we decide on a certain version, the number of necessary changes overwhelms us, we end up with the last version with which we managed to rebuild the application ;
3. Old version from [node archive](https://nodejs.org/en/about/previous-releases)
4. With each new build, we remove node_modules and lock package for the two projects in which we call npm install to make sure that we have the correct library versions set and the project is built on a given node version:
  - ...\Scada-LTS\scadalts-ui\node_modules (and revert/rollback)
  - ...\Scada-LTS\scadalts-ui\package-lock.json
  - ...\Scada-LTS\WebContent\resources\package-lock.json
  - ...\Scada-LTS\WebContent\resources\node_modules
5. You can follow my upgrade to node 14: https://github.com/SCADA-LTS/Scada-LTS/pull/2366/files
6. Once you have made the necessary changes, you can create a pullrequest and create a patch to upload:
https://www.jetbrains.com/help/idea/using-patches.html
7. If you use Windows and it is version >7, do not worry about the compatibility of the node with Windows version <= 7. (It's an outdated system, we don't support it) If you are working on windows <=7, you will most likely have problems with node running for versions >14.

Remember to focus on the essence of the task and not get distracted by other things that are not even recommended here.
I wish you a happy new year.

Regards,
Kamil Jarmusik

**Comment by RenatoExpert** [comment]
@Limraj Thank you for replying!
My focus will remain on Nodejs, and I agree with you that doing too much outside is not a good practice.
I will keep using my changes on docker and gradle, because they are convient for me, but after upgrade is done, i am going to remove these changes before pull request. So you will get only `scadalts-ui/` changes.

**Comment by Limraj** [comment]
Hi @RenatoExpert,
Just start over and try to apply my suggestions, the commit history should only include changes that go into the source code.

Regards,
Kamil Jarmusik

**Comment by Limraj** [comment]
Hi @RenatoExpert,
I'am created issue for you:
https://github.com/SCADA-LTS/Scada-LTS/issues/2805

Regards,
Kamil Jarmusik

**Comment by Limraj** [comment]
@RenatoExpert do you understand how you should approach this task?

you need to close this pr and try again

**Comment by Limraj** [comment]
Hi @RenatoExpert,
we see that you have devoted some time to our project, so we wanted to invite you to the team. Wait for an invitation, then you will be able to directly create branches in our repository and work like others in the team. I hope that we will be able to upgrade the node version to the newer lts version, it will be a big help for us.

Instructions for creating issues, branches and commits - it is important that you follow these rules:

a) You start the release/x branch (x - the version of the application we are currently working on, currently it is version 2.7.7). You create a branch with the name:
fix/#<number_issue>_<title_issue> - at the beginning fix/#, separate the words with` _`, replace <number_issue> and <title_issue> with appropriate values;

or 

feature/#<number_issue>_<title_issue>

b) After changing the code, you create a commit with a message as follows:
#<number_issue> - <title_issue> - what did you change and why;
and commit to branch create for issue from point a)

c) You do a push, create a pullrequest to release/x and send me a review request;
d) I do a code review and if OK, I merge the changes to the release/x branch;
e) When creating an issue, try to use our templates, after clicking 'New issue' in github, select the appropriate template and try to complete it;

Regards,
Kamil Jarmusik

**Comment by RenatoExpert** [comment]
Hi @Limraj!
> we see that you have devoted some time to our project, so we wanted to invite you to the team.

I am glad to be helpful, and I apreciate the trust.

> @RenatoExpert do you understand how you should approach this task?
you need to close this pr and try again

No problem, and sorry for late answer. I had sometime not logging in github this month.

I will try to make this update again, following the new instructions, in 2 or 3 weeks.

**Comment by RenatoExpert** [comment]
Good afternoon @Limraj! 
> we see that you have devoted some time to our project, so we wanted to invite you to the team. Wait for an invitation, then you will be able to directly create branches in our repository and work like others in the team. I hope that we will be able to upgrade the node version to the newer lts version, it will be a big help for us.

I did not receive any invitation yet. :c

**Pull request closed without merging**
